package token

import (
	"fmt"
)

type TokenType string

const (
	// SPECIAL
	ILLEGAL     = "ILLEGAL"
	END_OF_FILE = "END_OF_FILE"

	// KEYWORDS
	LET      = "LET"
	FUNCTION = "FUNCTION"
	RETURN   = "RETURN"

	// IDENTIFIERS
	IDENTIFIER = "IDENTIFIER"

	// LITERALS
	INTEGER_LITERAL = "INTEGER_LITERAL"
	STRING_LITERAL  = "STRING_LITERAL"
	FLOAT_LITERAL   = "FLOAT_LITERAL"
	BOOLEAN_LITERAL = "BOOLEAN_LITERAL"

	// OPERATORS
	PLUS     = "PLUS"
	MINUS    = "MINUS"
	MULTIPLY = "MULTIPLY"
	DIVIDE   = "DIVIDE"
	ASSIGN   = "ASSIGN"

	// COMPARISON OPERATORS
	IS_EQUAL                 = "IS_EQUAL"
	IS_NOT_EQUAL             = "IS_NOT_EQUAL"
	IS_LESS_THAN             = "IS_LESS_THAN"
	IS_GREATER_THAN          = "IS_GREATER_THAN"
	IS_LESS_THAN_OR_EQUAL    = "IS_LESS_THAN_OR_EQUAL"
	IS_GREATER_THAN_OR_EQUAL = "IS_GREATER_THAN_OR_EQUAL"

	// DELIMITERS
	COMMA     = "COMMA"
	SEMICOLON = "SEMICOLON"

	// SYMBOLS
	LEFT_PAREN  = "LEFT_PAREN"
	RIGHT_PAREN = "RIGHT_PAREN"
	LEFT_BRACE  = "LEFT_BRACE"
	RIGHT_BRACE = "RIGHT_BRACE"
)

type Token struct {
	Type    TokenType
	Literal string
}

func (token Token) String() string {
	return fmt.Sprintf("Token(%s, %s)", token.Type, token.Literal)
}
